// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
)

type Player struct {
	Playerid              int64
	Username              string
	Figurestring          sql.NullString
	Motto                 sql.NullString
	Membersince           sql.NullTime
	Userdataexists        sql.NullBool
	Figureexists          sql.NullBool
	Userdatalastrequested sql.NullTime
	Figurelastrequested   sql.NullTime
	AvatarExists          sql.NullBool
	AvatarLastRequested   sql.NullTime
}
